### ISSUE TITLE
Clean up train/test splits

### ISSUE THREAD

**Issue by pasky** [AugurProject/argus#1]
We should do a train/test split on input data before processing anything, not just when reporting the results, to ensure that proper data hygiene is kept.

(At a later time, we should also further split the train to trainmodel and val and perform learning of sub-classifiers like the sentiment on trainmodel and measure its performance on val rather than test, so that we don't overfit by parameter tuning. However, we have too little data to afford that at this point, so it's just something to bear in mind for now.)

**Comment by Silvicek** [comment]
Delt with long time ago
