### ISSUE TITLE
Odd commodity output for Aluminium

### ISSUE THREAD

**Issue by tealmill** [AugurProject/argus#9]
When using the benchtest script, the output for the text question regarding aluminium is odd; despite wide date range being selected, both min and max values are the same value and both refer to the same day. Is only a single data point being utilized to describe the entire range?
- [x] Implement proper search for the minimal/maximal day in the range or define special behaviour.

**Comment by nelibjir** [comment]
It's not the bug of the script, but the API for calling COMEX with aluminium returns only this day, because in the API are data only from 03-30-2016 until now. So I changed the question, more precisely the end date to 2016-06-30. Another possibility would be to change the market.

**Comment by pasky** [comment]
Thanks! So can we close this?

**Comment by nelibjir** [comment]
yes and sorry for the time delay in response
